name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build -- --configuration=production --base-href "/blog-admin-angular/"

      # 找出 Angular 17+ 的 dist/*/browser 或較舊版的 dist/* 目錄
      - id: vars
        run: |
          if [ -d dist/*/browser ]; then
            echo "dir=$(ls -d dist/*/browser)" >> $GITHUB_OUTPUT
          else
            echo "dir=$(ls -d dist/*)" >> $GITHUB_OUTPUT
          fi

      # 解決前端路由在 GH Pages 刷新 404 的問題
      - run: cp "${{ steps.vars.outputs.dir }}/index.html" "${{ steps.vars.outputs.dir }}/404.html"

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.vars.outputs.dir }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
